<?php
    $domain = \Techy\Config\Domain::instance()->main();
    $authurl = $domain .
        \Techy\Lib\Core\System\Application::instance()->getRouter()->getRoute( 'get', 'authorization\\PasswordRecovery', 'newPassword', $d );

    echo <<<HTML
Здравствуйте, {$d['name']}!
<br />
<br />На сервисе <a href="$domain">$domain</a>
<br />была запрошена информация для смены вашего пароля.
<br />
<br />Для создания нового пароля, пожалуйста, перейдите по ссылке:
<br /><a href="$authurl">$authurl</a>
HTML;
