<nav class="navbar navbar-default">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="#">БРЕНД</a>
        </div>
        <ul class="nav navbar-nav">
            <li><a href="/admin/home/">Главная</a></li>
            <li><a href="/admin/users/">Пользователи</a></li>
            <li><a href="/admin/admins/">Админы</a></li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
            <li><a href="signout">Выход</a></li>
        </ul>
    </div>
</nav>