<head>
    <meta charset="utf-8" />
    <title></title>
    <meta name="viewport" content="width=640, minimum-scale=0.5, maximum-scale=3.0, user-scalable=yes, target-densitydpi=device-dpi"/>
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="keywords" content="" />

    <?= \Techy\Config\Assets::styles() ?>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="/js/assets/html5shiv.js"></script>
    <script src="/js/assets/respond.min.js"></script>
    <![endif]-->
</head>
