<div style="width: 450px; margin: 80px auto;">
    <form action="/auth/signin" method="post" id="signInForm">
        <fieldset class="panel panel-default">
            <div class="panel-heading">АВТОРИЗАЦИЯ</div>
            <div class="panel-body">
                <div class="-form-errors-"></div>

                <div class="form-group -login-">
                    <input type="text" name="login" class="form-control input-lg" placeholder="введите логин" />
                    <span class="help-block -error-"></span>
                </div>

                <div class="form-group -password-">
                    <input type="password" name="password" class="form-control input-lg" placeholder="введите пароль" />
                    <span class="help-block -error-"></span>
                </div>
            </div>
            <div class="panel-footer text-right">
                <a href="/auth/recovery" class="pull-left">Забыли пароль?</a>
                <button type="submit" class="btn btn-lg btn-primary">Войти</button>
            </div>
        </fieldset>
    </form>
</div>
