<div style="width: 450px; margin: 80px auto;">
    <form action="/<?= \Techy\Lib\Core\System\Application::instance()->getRouter()->getRoute( 'post', 'authorization\\PasswordRecovery', 'newPasswordSubmit', $d ) ?>" method="post" id="newPasswordForm">
        <fieldset class="panel panel-default">
            <div class="panel-heading">ВОССТАНОВЛЕНИЕ ПАРОЛЯ</div>
            <div class="panel-body">
                <div class="-form-errors-">
                    <div class="alert alert-info">
                        Теперь вы можете установить новый пароль.
                    </div>
                </div>

                <div class="form-group -password-">
                    <label class="control-label">Новый пароль</label>
                    <input type="password" name="password" class="form-control input-large" />
                    <span class="help-inline -error-"></span>
                </div>
                <div class="form-group -password2-">
                    <label class="control-label">Повторите пароль</label>
                    <input type="password" name="password2" class="form-control input-large" />
                    <span class="help-inline -error-"></span>
                </div>
            </div>
            <div class="panel-footer text-right">
                <a href="/" class="pull-left">На главную</a>
                <button type="submit" class="btn btn-lg btn-primary">Завершить восстановление</button>
            </div>
        </fieldset>
    </form>
</div>
