<div style="width: 450px; margin: 80px auto;">
    <form action="/auth/recovery" method="post" id="passwordRecoveryForm">
        <fieldset class="panel panel-default">
            <div class="panel-heading">ВОССТАНОВЛЕНИЕ ПАРОЛЯ</div>
            <div class="panel-body">
                <div class="-form-errors-"></div>

                <div class="form-group -field-container-">
                    <input type="text" name="login" class="form-control input-large" placeholder="ivan@gmail.com" />
                    <span class="help-inline -error-"></span>
                </div>
            </div>
            <div class="panel-footer text-right">
                <a href="/" class="pull-left">Назад</a>
                <button type="submit" class="btn btn-lg btn-primary">Продолжить</button>
            </div>
        </fieldset>
    </form>
</div>

